name = "BoundedRationals"
uuid = "55f81f2a-010d-11ea-2966-71af6acb0a39"
authors = ["bhgomes <bhgomes.github@gmail.com>"]
version = "0.1.0"

[deps]
AbstractRationals = "4958c51a-00f6-11ea-2b94-f3f784e4d148"

[compat]
julia = "1"
